### PR TITLE
Fixed false ontology_ref requirment

### PR DESCRIPTION
**Pull request by jkbaumohl**

### CODE REVIEW

**Review by jayrbolton — APPROVED** [review]
As discussed in slack, LGTM

**Comment by jayrbolton** [comment]
It looks like I have powers to merge this now without the other two reviewers doing a review.
Before I do so, @jkbaumohl can you increment the patch version in kbase.yml? And also add a short note in the changelog about this fix. Then we can deploy to CI at some point.

**Review by slebras — APPROVED** [review]
looks good

**Comment by dcchivian** [comment]
will register this v0.11.2 up to beta on CI and up to dev on APPDEV/PROD.  will require additional testing before release of module.

**Pull request merged**
