### PR TITLE
gff_fasta_to_genome refactor

### PR DESCRIPTION
**Pull request by Tianhao-Gu**

### CODE REVIEW

**Comment by Tianhao-Gu** [comment]
@msneddon @samseaver Could you review this PR? Thanks.

**Comment by msneddon** [comment]
Code all looks good to me.  Tests pass against CI for me with pretty good coverage.  I can't comment though on whether the generated genome objects look correct?  @samseaver have or can you verify that the upload logic is correct?

I just have two minor comments-
1) we should make this change be a minor version bump, not just a patch version bump, and 
2) are we planning to add an uploader app spec in this module, or do we plan to only support this from the staging area uploaders or with an app spec in a different module?

**Comment by Tianhao-Gu** [comment]
@msneddon Thanks. Bumped minor version. I think currently @samseaver only wants this to work with staging files. So I will implement the UI and function call in kb_uploadmethods.

**Comment by samseaver** [comment]
I just got back from vacation. The approach is dependent on at least two input files, so, for the time being, it can only work with using two staged files.

Thanks for merging, I did check the output genome object of the tests themselves, and it looked good.

Next step is to use this with kb_uploadmethods, however, I'd like to stay on top of how this particular PR is available in the various environments. I can go to the app catalog and double-check the commits, but where would you announce that you're promoting this?  The key here is that, for now, I have to use 'dev' for the SDK Callback.

**Pull request merged**
